spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketdb
    username: ticketadmin
    password: 321654
  jpa:
    hibernate:
      ddl-auto: validate # Tabloları ORM değil, Flyway yönetecek
    show-sql: true
  flyway:
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/TicketSystemRealm