input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["ticket-logs"]
    codec => json
    group_id => "logstash-consumer-group"
  }
}

output {
  opensearch {
    hosts => ["http://opensearch:9200"]
    index => "otel-logs"
    ssl_certificate_verification => false
  }
  stdout { codec => rubydebug } 
}