server {
    listen       80;
    server_name  localhost;

    # Gzip sikistirma
    gzip on;
    gzip_types text/plain text/css application/json application/javascript
               text/xml application/xml application/xml+rss text/javascript;

    # Derlenmis React dosyalarini servis eder.
    # SPA icin bilinmeyen tum path'leri index.html'e yonlendirir.
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}
