apiVersion: v1
kind: Service
metadata:
  name: it-service-frontend
  labels:
    app.kubernetes.io/name: it-service-frontend
    app.kubernetes.io/component: frontend
spec:
  selector:
    app.kubernetes.io/name: it-service-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
