apiVersion: v1
kind: Service
metadata:
  name: it-service-backend
  labels:
    app.kubernetes.io/name: it-service-backend
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: it-service-backend
  ports:
    - name: http
      port: 8081
      targetPort: 8081
