apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - it-service-backend-service.yaml
  - it-service-backend-deployment.yaml
  - llm-service-service.yaml
  - llm-service-deployment.yaml
