-- 1. BAĞIMSIZ TABLOLAR (Başka bir tabloya referansı olmayanlar)



CREATE TABLE users (

    id VARCHAR(36) PRIMARY KEY, -- Keycloak'tan gelecek UUID

    email VARCHAR(255) UNIQUE NOT NULL,

    full_name VARCHAR(100) NOT NULL,

    role VARCHAR(20) NOT NULL,

    is_active BOOLEAN DEFAULT TRUE,

    created_at TIMESTAMPTZ DEFAULT NOW()

);



CREATE TABLE products (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(255) NOT NULL,

    is_active BOOLEAN DEFAULT TRUE

);



CREATE TABLE sla_policies (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    priority VARCHAR(10) UNIQUE NOT NULL,

    target_resolution_hours INTEGER NOT NULL,

    created_at TIMESTAMPTZ DEFAULT NOW()

);



-- 2. ANA TABLO: BİLETLER (TICKETS)



CREATE TABLE tickets (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    title VARCHAR(500) NOT NULL,

    description TEXT NOT NULL,

    status VARCHAR(30) NOT NULL,

    priority VARCHAR(10) NOT NULL,

    product_id BIGINT,

    customer_id VARCHAR(36) NOT NULL,

    assignee_id VARCHAR(36),

    sla_deadline TIMESTAMPTZ,

    sla_breached BOOLEAN DEFAULT FALSE,

    created_at TIMESTAMPTZ DEFAULT NOW(),

    resolved_at TIMESTAMPTZ,

    closed_at TIMESTAMPTZ,

   

    -- Foreign Key Kısıtlamaları

    CONSTRAINT fk_ticket_product FOREIGN KEY (product_id) REFERENCES products(id),

    CONSTRAINT fk_ticket_customer FOREIGN KEY (customer_id) REFERENCES users(id),

    CONSTRAINT fk_ticket_assignee FOREIGN KEY (assignee_id) REFERENCES users(id),

    CONSTRAINT fk_ticket_sla FOREIGN KEY (priority) REFERENCES sla_policies(priority)

);



-- 3. BİLETE BAĞLI ALT TABLOLAR (Yorumlar, Eforlar, Dosyalar, Anketler)



CREATE TABLE ticket_comments (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    ticket_id BIGINT NOT NULL,

    author_id VARCHAR(36) NOT NULL,

    message TEXT NOT NULL,

    type VARCHAR(10) NOT NULL, -- INTERNAL veya EXTERNAL

    created_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT fk_comment_ticket FOREIGN KEY (ticket_id) REFERENCES tickets(id),

    CONSTRAINT fk_comment_author FOREIGN KEY (author_id) REFERENCES users(id)

);



CREATE TABLE ticket_worklogs (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    ticket_id BIGINT NOT NULL,

    agent_id VARCHAR(36) NOT NULL,

    minutes INTEGER NOT NULL,

    description VARCHAR(500),

    created_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT fk_worklog_ticket FOREIGN KEY (ticket_id) REFERENCES tickets(id),

    CONSTRAINT fk_worklog_agent FOREIGN KEY (agent_id) REFERENCES users(id)

);



CREATE TABLE ticket_attachments (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    ticket_id BIGINT NOT NULL,

    uploader_id VARCHAR(36) NOT NULL,

    file_name VARCHAR(255) NOT NULL,

    file_type VARCHAR(100) NOT NULL,

    content BYTEA NOT NULL, -- Dosyanın kendisi (Binary)

    created_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT fk_attachment_ticket FOREIGN KEY (ticket_id) REFERENCES tickets(id),

    CONSTRAINT fk_attachment_uploader FOREIGN KEY (uploader_id) REFERENCES users(id)

);



CREATE TABLE csat_surveys (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    ticket_id BIGINT UNIQUE NOT NULL, -- Bir biletin sadece bir anketi olabilir

    rating INTEGER NOT NULL,

    comment TEXT,

    created_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT fk_csat_ticket FOREIGN KEY (ticket_id) REFERENCES tickets(id)

);



-- 4. BİLDİRİMLER



CREATE TABLE notifications (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id VARCHAR(36) NOT NULL,

    message TEXT NOT NULL,

    is_read BOOLEAN DEFAULT FALSE,

    created_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES users(id)

);