-- Talep konuları (ticket topics) bir ürünün altındaki seçilebilir konu listesini tutar.
-- Bilet oluşturulurken müşteri önce ürün, ardından bu listeden bir konu seçer.

CREATE TABLE IF NOT EXISTS ticket_topics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_ticket_topics_product_name UNIQUE (product_id, name)
);

CREATE INDEX IF NOT EXISTS idx_ticket_topics_product_active
    ON ticket_topics (product_id, is_active);

-- Bilet üzerinde konu referansı.
-- topic_id: kaynak konuya zorunlu bağlantı (NOT NULL).
-- ON DELETE RESTRICT: kendisine bağlı bilet varsa konu silinemez; admin önce `is_active=false`
-- yapmalı veya bu konudaki biletleri taşımalı.
-- topic_name_snapshot: konunun bilet oluşturulduğu andaki adı; konu yeniden adlandırılsa bile
-- geçmiş biletlerde doğru ad görünmeye devam eder.
ALTER TABLE tickets
    ADD COLUMN IF NOT EXISTS topic_id BIGINT NOT NULL REFERENCES ticket_topics(id) ON DELETE RESTRICT,
    ADD COLUMN IF NOT EXISTS topic_name_snapshot VARCHAR(255);

CREATE INDEX IF NOT EXISTS idx_tickets_topic_id ON tickets (topic_id);
