-- Çözüm Notu Tablosu (One-to-One with tickets)
-- Sadece bilete atanmış (claim'li) agent yazabilir.
-- Manager tüm çözüm notlarını görebilir.

CREATE TABLE ticket_resolution_notes (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    ticket_id BIGINT UNIQUE NOT NULL, -- One-to-one: bir biletin yalnızca bir çözüm notu olabilir

    agent_id VARCHAR(36) NOT NULL,    -- Notu yazan agent (ticket.assignee_id ile eşleşmeli)

    note TEXT NOT NULL,

    created_at TIMESTAMPTZ DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT fk_resolution_note_ticket FOREIGN KEY (ticket_id) REFERENCES tickets(id),

    CONSTRAINT fk_resolution_note_agent FOREIGN KEY (agent_id) REFERENCES users(id)

);
