apiVersion: v1
kind: Service
metadata:
  name: data-prepper
  labels:
    app.kubernetes.io/name: data-prepper
    app.kubernetes.io/component: observability
spec:
  selector:
    app.kubernetes.io/name: data-prepper
  ports:
    - name: otlp-metrics
      port: 21891
      targetPort: 21891
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-prepper
  labels:
    app.kubernetes.io/name: data-prepper
    app.kubernetes.io/component: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: data-prepper
  template:
    metadata:
      labels:
        app.kubernetes.io/name: data-prepper
        app.kubernetes.io/component: observability
    spec:
      containers:
        - name: data-prepper
          image: opensearchproject/data-prepper:2.10.2
          ports:
            - name: otlp-metrics
              containerPort: 21891
          volumeMounts:
            - name: config
              mountPath: /usr/share/data-prepper/pipelines/pipelines.yaml
              subPath: pipelines.yaml
            - name: config
              mountPath: /usr/share/data-prepper/config/data-prepper-config.yaml
              subPath: data-prepper-config.yaml
      volumes:
        - name: config
          configMap:
            name: data-prepper-config
