apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - redis-service.yaml
  - redis-statefulset.yaml
  - mailpit-service.yaml
  - mailpit-deployment.yaml
  - kafka-service.yaml
  - kafka-statefulset.yaml
  - opensearch-service.yaml
  - opensearch-statefulset.yaml
  - opensearch-dashboards-deployment.yaml
  - otel-collector-deployment.yaml
  - data-prepper-deployment.yaml
  - logstash-deployment.yaml

configMapGenerator:
  - name: otel-collector-config
    files:
      - otel-collector-config.yaml=../../../otel-collector-config.yaml
  - name: logstash-pipeline
    files:
      - logstash.conf=../../../logstash.conf
  - name: data-prepper-config
    files:
      - pipelines.yaml=../../../data-prepper/pipelines.yaml
      - data-prepper-config.yaml=../../../data-prepper/data-prepper-config.yaml

generatorOptions:
  disableNameSuffixHash: true
