package com.ticketsystem.it_service_backend.service;

import com.ticketsystem.it_service_backend.entity.Product;
import com.ticketsystem.it_service_backend.repository.AgentProductLimitRepository;
import com.ticketsystem.it_service_backend.repository.ProductRepository;
import com.ticketsystem.it_service_backend.repository.TicketRepository;
import com.ticketsystem.it_service_backend.repository.UserRepository;
import com.ticketsystem.it_service_backend.entity.User;
import com.ticketsystem.it_service_backend.util.AuthRoles;
import com.ticketsystem.it_service_backend.util.LocalizedText;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

import java.util.ArrayList;
import java.util.List;

import lombok.extern.log4j.Log4j2;

/**
 * Product CRUD and per-user product access control.
 *
 * <p>Customer/agent users can only see products that appear in their
 * {@code authorized_products} relationship; ADMIN and MANAGER see every
 * product. Product deletion is cascading: all related tickets are removed via
 * {@link TicketService#deleteTicket} calls, then agent-specific limit records
 * are cleared.
 */
@Log4j2
@Service
@RequiredArgsConstructor
public class ProductService {

    private final ProductRepository productRepository;
    private final UserRepository userRepository;
    private final TicketService ticketService;
    private final TicketRepository ticketRepository;
    private final AgentProductLimitRepository agentProductLimitRepository;

    /**
     * Returns the product by ID after verifying the caller's access.
     * ADMIN / MANAGER bypass the check; other roles must have the product
     * in their {@code user.authorizedProducts} list.
     *
     * @param id product ID
     * @param userId requesting user
     * @param roles role list of the user
     * @return the product
     * @throws ResponseStatusException 404 if product/user missing, 403 on missing access
     */
    @Transactional(readOnly = true)
    public Product getProductById(Long id, String userId, List<String> roles) {
        Product product = productRepository.findById(id)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "error.product.not.found"));

        if (AuthRoles.isGlobal(roles)) return product;

        if (userId == null) throw new ResponseStatusException(HttpStatus.FORBIDDEN, "error.forbidden");

        User user = userRepository.findById(userId)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "error.user.not.found"));

        boolean authorized = user.getAuthorizedProducts().stream()
                .anyMatch(p -> p.getId().equals(id));
        if (!authorized) throw new ResponseStatusException(HttpStatus.FORBIDDEN, "error.product.access.forbidden");

        return product;
    }

    /**
     * Returns all products the user can see. ADMIN / MANAGER receive every
     * product; other roles get only their own {@code authorizedProducts}. Returns
     * an empty list when the user ID is null.
     *
     * @param userId requesting user (may be null)
     * @param roles role list of the user
     * @return visible products
     */
    @Transactional(readOnly = true)
    public List<Product> getAllProducts(String userId, List<String> roles) {
        log.debug("Ürün listeleme isteği. Kullanıcı: {}, Roller: {}", userId, roles);

        if (AuthRoles.isGlobal(roles)) {
            log.debug("Global rol algılandı (ADMIN/MANAGER), tüm ürünler getiriliyor.");
            return productRepository.findAll();
        }
        
        if (userId == null) {
            log.warn("Kullanıcı ID bulunamadı, boş liste dönülüyor.");
            return new ArrayList<>();
        }

        User user = userRepository.findById(userId)
                .orElseThrow(() -> {
                    log.error("Kullanıcı veritabanında bulunamadı: {}", userId);
                    return new RuntimeException("Kullanıcı bulunamadı: " + userId);
                });

        List<Product> authProducts = user.getAuthorizedProducts();
        log.debug("Kullanıcı (ID: {}) için {} adet yetkili ürün bulundu.", userId, authProducts.size());
        return authProducts;
    }

    /**
     * Creates a new product. At least one name variant (tr/en) must be non-blank;
     * {@code isActive} defaults to {@code true} when null.
     *
     * @param product product to create (ID is generated by the DB)
     * @return the persisted product
     * @throws ResponseStatusException 400 if both name variants are blank
     */
    public Product createProduct(Product product) {
        product.setNameTr(normalize(product.getNameTr()));
        product.setNameEn(normalize(product.getNameEn()));
        if (product.getNameTr() == null && product.getNameEn() == null) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "error.product.name.required");
        }
        validateMaxActiveTickets(product.getMaxActiveTickets());
        log.info("Yeni ürün oluşturuluyor: {}", LocalizedText.label(product.getNameTr(), product.getNameEn()));
        if (product.getIsActive() == null) {
            product.setIsActive(true);
        }
        Product savedProduct = productRepository.save(product);
        log.info("Ürün başarıyla oluşturuldu. ID: {}", savedProduct.getId());
        return savedProduct;
    }

    /**
     * Cascade-deletes the product along with all related ticket and limit records.
     *
     * <p>First, all ticket IDs under the product are collected and each is removed
     * via {@link TicketService#deleteTicket} (so comments, attachments, claims,
     * etc. are cleaned up). Agent-specific limit records and the product itself
     * are then deleted.
     *
     * @param id product ID to delete
     */
    @Transactional
    public void deleteProduct(Long id) {
        log.info("Ürün siliniyor. ID: {}", id);

        // Ürüne bağlı tüm biletleri ve onlara ait tüm verileri sil
        List<Long> ticketIds = ticketRepository.findByProductId(id)
                .stream().map(t -> t.getId()).toList();

        if (!ticketIds.isEmpty()) {
            log.info("Ürüne bağlı {} bilet cascade siliniyor. Ürün ID: {}", ticketIds.size(), id);
            for (Long ticketId : ticketIds) {
                ticketService.deleteTicket(ticketId);
            }
        }

        agentProductLimitRepository.deleteByProductId(id);
        productRepository.deleteById(id);
        log.info("Ürün başarıyla silindi. ID: {}", id);
    }

    /**
     * Partially updates the product. Only non-{@code null} fields are applied;
     * sending {@code maxActiveTickets} explicitly as {@code null} clears the limit.
     *
     * @param id product ID to update
     * @param updatedProduct partial new values
     * @return the updated product
     * @throws RuntimeException if the product is not found
     */
    public Product updateProduct(Long id, Product updatedProduct) {
        log.info("Ürün güncelleniyor. ID: {}", id);
        Product existingProduct = productRepository.findById(id)
                .orElseThrow(() -> {
                    log.error("Güncellenecek ürün bulunamadı. ID: {}", id);
                    return new RuntimeException("Ürün bulunamadı: " + id);
                });

        // İki ad alanından en az biri geldiyse çift tam ad güncellemesi kabul edilir;
        // boş gönderilen varyant o dili temizler (ikisi birden boş kalamaz).
        if (updatedProduct.getNameTr() != null || updatedProduct.getNameEn() != null) {
            String tr = normalize(updatedProduct.getNameTr());
            String en = normalize(updatedProduct.getNameEn());
            if (tr == null && en == null) {
                throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "error.product.name.required");
            }
            log.debug("İsim güncelleniyor: {} -> {}",
                    LocalizedText.label(existingProduct.getNameTr(), existingProduct.getNameEn()),
                    LocalizedText.label(tr, en));
            existingProduct.setNameTr(tr);
            existingProduct.setNameEn(en);
        }
        if (updatedProduct.getIsActive() != null) {
            log.debug("Aktiflik durumu güncelleniyor: {} -> {}", existingProduct.getIsActive(), updatedProduct.getIsActive());
            existingProduct.setIsActive(updatedProduct.getIsActive());
        }
        if (updatedProduct.getMaxActiveTickets() != null) {
            validateMaxActiveTickets(updatedProduct.getMaxActiveTickets());
            log.debug("Maksimum eşzamanlı bilet limiti güncelleniyor: {} -> {}", existingProduct.getMaxActiveTickets(), updatedProduct.getMaxActiveTickets());
            existingProduct.setMaxActiveTickets(updatedProduct.getMaxActiveTickets());
        } else if (updatedProduct.getMaxActiveTickets() == null && existingProduct.getMaxActiveTickets() != null) {
            log.debug("Maksimum eşzamanlı bilet limiti kaldırılıyor");
            existingProduct.setMaxActiveTickets(null);
        }
        Product savedProduct = productRepository.save(existingProduct);
        log.info("Ürün başarıyla güncellendi. ID: {}", savedProduct.getId());
        return savedProduct;
    }

    /**
     * Updates the product's default concurrent ticket limit; passing {@code null}
     * removes the limit entirely. Non-positive values are rejected.
     *
     * @param productId product ID
     * @param limit new limit, or {@code null} to remove
     * @return the updated product
     * @throws IllegalArgumentException if limit is below 1
     * @throws ResponseStatusException 404 if the product is not found
     */
    /**
     * Validates the concurrent ticket limit bounds. A {@code null} limit means
     * "unlimited" and is always allowed; otherwise it must be in {@code 1..10000}.
     *
     * @param limit limit to validate, or {@code null} for unlimited
     * @throws IllegalArgumentException if the limit is below 1 or above 10000
     */
    private void validateMaxActiveTickets(Integer limit) {
        if (limit == null) {
            return;
        }
        if (limit < 1) {
            throw new IllegalArgumentException("error.product.limit.minimum");
        }
        if (limit > 10000) {
            throw new IllegalArgumentException("error.product.limit.maximum");
        }
    }

    @Transactional
    public Product updateMaxActiveTickets(Long productId, Integer limit) {
        log.info("Ürün eşzamanlı bilet limiti güncelleniyor. ID: {}, Yeni limit: {}", productId, limit);

        validateMaxActiveTickets(limit);

        Product existingProduct = productRepository.findById(productId)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "error.product.not.found"));

        existingProduct.setMaxActiveTickets(limit);

        Product savedProduct = productRepository.save(existingProduct);
        log.info("Ürün eşzamanlı bilet limiti güncellendi. ID: {}, Limit: {}", savedProduct.getId(), savedProduct.getMaxActiveTickets());
        return savedProduct;
    }

    /** Trims and converts blank to {@code null} so "cleared" and "absent" collapse to one state. */
    private String normalize(String name) {
        if (name == null) return null;
        String trimmed = name.trim();
        return trimmed.isEmpty() ? null : trimmed;
    }
}