apiVersion: v1
kind: Service
metadata:
  name: kie-server
  labels:
    app.kubernetes.io/name: kie-server
    app.kubernetes.io/component: workflow
spec:
  selector:
    app.kubernetes.io/name: kie-server
  ports:
    - name: http
      port: 8080
      targetPort: 8080
