// Aksiyon türü → seçilebilir sebep kodlarının listesi.
// Etiketler i18next üzerinden okunur: t(`reasonCode.${ACTION}.${CODE}`).

export const REASON_CODES = {
  UNCLAIM: ['INSUFFICIENT_KNOWLEDGE', 'WORKLOAD', 'OUT_OF_SCOPE', 'REASSIGNMENT_NEEDED', 'OTHER'],
  RESOLVE: ['SOLUTION_PROVIDED', 'INFORMATION_GIVEN', 'WORKAROUND_PROVIDED', 'CONFIGURATION_CHANGE', 'ROOT_CAUSE_FIXED', 'OTHER'],
  CLOSE:   ['RESOLVED_CONFIRMED', 'NO_RESPONSE', 'DUPLICATE', 'INVALID', 'CUSTOMER_REQUEST', 'OTHER'],
  PRIORITY_CHANGE: ['CUSTOMER_IMPACT', 'BUSINESS_URGENCY', 'SLA_REASSESSMENT', 'INCORRECT_INITIAL', 'OTHER'],
  TOPIC_CHANGE:    ['MISCATEGORIZED', 'SCOPE_REFINED', 'ROOT_CAUSE_DIFFERENT', 'CUSTOMER_CLARIFIED', 'OTHER'],
};

export const OTHER_REASON_CODE = 'OTHER';
